### ISSUE TITLE
Instructions for RTC

### ISSUE THREAD

**Issue by adamoutler** [merky1/PiClock#37]
When starting the clock from a cold boot, some of the artifacts don't show up due to missing time which I believe is causing failure to communicate with servers.  

Real time clock should be set up and recommended for installation. Additionally, the clock should not be started until a successful NTP/chrony sync has occurred. 

I believe the problems with gadgets not showing up sometimes is due to this.  It was corrected on my machine by installation of a RTC.  

Picture showing gadget on right which shows up directly AT 30-second mark from plugging in on RPI4.
![IMG_20200811_224434](https://user-images.githubusercontent.com/527919/89969438-63d41c00-dc24-11ea-8312-6dafc49ec58b.jpg)

Picture showing cheap and easy RTC installed
![IMG_20200811_224416](https://user-images.githubusercontent.com/527919/89969473-777f8280-dc24-11ea-8fb0-4edddc0c6e27.jpg)

**Comment by merky1** [comment]
so the issue is that the NOAA site is temperamental with pulling the forecast.  I’ve protected the backend by setting retries and polling delays, but the front end will not display any blocks until the forecast loads, and this could take a while. 

I’ve been contemplating updating the client.js to account for this, but I’d have to rewrite the timer intervals.  The other option is to have the backend poll CC or OW for the forecast as a fallback.  I’ve let this linger since it is a NOAA availability issue, and seems to self correct after a short time.

To verify, check the Piclock log for Forecast pulls.

What i should do is implement a callback to load the client when the forecast loads.  I am just have not put a lot of thought into this since it’s more of a NOAA issue.

**Comment by adamoutler** [comment]
I was experiencing the issue on each boot up previously.  However the issue entirely stopped after I installed a RTC module which leads me to believe it is a problem establishing https connection with improper time.

**Comment by merky1** [comment]
So I’ve done some rewriting of backend, and I think I have a better understanding of what is / was happening.

First, keep in mind that to use NWS weather, you need at least 2 calls.  The first is a call to determine the local station IDs for subsequent calls.  The second, and essentially all of the following calls use these data points in the API.  

The problem lies in that the NWS API fails intermittently, and I was handling these failures poorly.  Part of the problem was in the async functions, part of it was PEBKAC assuming the API was solid.  Since the NWS site intermittently fails, the forecast fails with missing station IDs.

I rewrote the polling code to facilitate quicker turn around if a provider needs to be added / subtracted.  I also added a retry concept on the station lookups and forecast pollers.  I’ve tested this model for > 2 months, and it seems to work better.
