### ISSUE TITLE
imgFontColor being overridden on main page

### ISSUE THREAD

**Issue by TekMasterGaming** [merky1/PiClock#42]
imgFontColor in settings.json is getting overwritten on web page load, i can see it in black for a split second then all text goes white

would like to be able to set the text to black on the whole page as it is hard to read on 7 inch screen

**Comment by TekMasterGaming** [comment]
seems that its only not working if i don't specify a background image, when i put an image in it works

**Comment by TekMasterGaming** [comment]
also the sub-windows that you open on the gmap and forecast buttons when they open they do not match the color and background scheme of the main page

**Comment by TekMasterGaming** [comment]
could you possibly help me with setting up eclipse to go through the code myself? i see some .setting files but not sure how to import to eclipse and setup the environment

**Comment by merky1** [comment]
So this is not so hard, since the calls for the color changes are encapsulated in the .js files.  I threw them together quickly, and did a poor job of planning things out.  I need to refactor the color sub to return values so I can escape font color changes.

I will look into this today, but client side is my kryptonite.

**Comment by merky1** [comment]
Line 299 in main starts the train wreck...

**Comment by merky1** [comment]
Mulling this over, I think the BEST thing to do is to move the color changing code to the backend, and then let the front end to “trust” the values set by the backend.

This would chop off all the client code in all the pages to a single source, instead of the copy/paste that I did in building the add on pages.

Until then, commenting line 299 in client.js should hold back the color updates.

**Comment by merky1** [comment]
Made initial pass at fixing this issue.  Pull the latest and see if that overrides the default behavior

**Comment by merky1** [comment]
It looks as if this method works, now I need to update the clock color changes.

![3DED0E35-ECAA-492B-B01E-7C0130E95861](https://user-images.githubusercontent.com/8691286/97191294-1f651080-177d-11eb-9b0f-19a0ecfc161f.png)

**Comment by merky1** [comment]
I think I got it...

![0E9AE18C-9784-4DFE-83AE-DEC99904E782](https://user-images.githubusercontent.com/8691286/97191985-d19cd800-177d-11eb-936e-f57b5b7a43b0.png)
