### ISSUE TITLE
Could you please provide us with a clear instruction? I'm new to this and I have no idea how to install that. Thank you!!!

### ISSUE THREAD

**Issue by ReJamDnB** [merky1/PiClock#6]

**Comment by merky1** [comment]
The project is no where near stable enough for me to work on install instructions.  Once I get out of development mode I will update the instruction set.  If someone else wants to update the instruction set, be my guest.

**Comment by merky1** [comment]
Thought I'd give an update.  Alerts are still untested (stupid good weather).  I was not updating the moon phases, so that should now be fixed.  Having some intermittent issues with my PI 3, so I wasn't sure if the browser issues were related to the hardware dying or chromium just sucking.

So now I have a new Pi 3+, and things seem stable on the current builds.  Still need to pass the run unattended for a week mark though.  

Short answer is this is still in hobbyist form, and nowhere ready for prime time.  For a more mature project, try https://magicmirror.builders/

**Comment by merky1** [comment]
Getting closer to stable.  Basically, I need to wait till winter to find out what the USG puts wind chill as in the API.  Other than that, things are running close to stable with all of the features I could think of.  I will start working on the documentation phase by the end of this week.

**Comment by Cooperstown39** [comment]
I tried the install instructions but get hung-up at the "npm install".  Displays the following;
saveError ENONT: no such file or directory, open 'home/package.json'
saveError EACCES: permission denied, open 'home/package-lock.json.3373704280'
enoent ENOENT: no such file or directory, open '/home/package.json'
home no description
home no repository field
home no README data
home no license field

I've tried running this from the root and home directories but same results. Any help would be appreciated.  Thanks!

**Comment by merky1** [comment]
You need to be in the PiClock directory.  Let me know if that fixes things.  I plan on doing a dry run with my second clock this weekend, so hopefully I can capture decent docs off of that.

**Comment by Cooperstown39** [comment]
Many thanks for the reply! Unfortunately, I keep getting the same results.  I've tried from the root, pi, pi/PiClock, and pi/PiClock/Clock. In all four cases I get the same message and it puts a file in that directory called package-lock.json.  I then rebooted and tried from scratch but with the same results.

**Comment by merky1** [comment]
I’m going to assume you didn’t run the git clone?  I didn’t doc it so that might have been missed..

**Comment by Cooperstown39** [comment]
That was the problem!  Ran the git clone, set-up the settings.json file and it runs. I seem to have a problem with the Google maps not displaying and there is no radar data.  I'm assuming the radar won't load until the maps show-up?  In the original PiClock, sometimes the map wouldn't appear but would still get the radar overlay. I ran this under the GUI (not light) so that may be part of the issue.  I'll burn a new SD image tomorrow and try it with the stretch lite version. Thanks for the help and program, it looks great!!

**Comment by Cooperstown39** [comment]
One more item, the first run works fine but if the program is closed and then re-started, the weather data on the right disappears (forecast).  A reboot and start fresh and it starts up OK (excepting the Google maps).

**Comment by merky1** [comment]
Give it 10 minutes.  I am finding that different USA forecast sites take a long time to return data.  Also, look in the logs for any error lines.  Google maps require a working api key now due google’s policy.  Once you get that in place things should load.

**Comment by Cooperstown39** [comment]
I'm not very familiar with linux so not sure what I'm doing on some of those command lines but I tried rebooting without the GUI and could not get anything to run. Something about the Display not found? Rebooted with the GUI and it is back up and running.  One of the problems with the map was operator error (mis-typed the API key).  Fixed the config file and the error message disappeared but now just a blank white box where the maps should be.  I'll let it run over night and report back if the maps show up and anything in the log files.

**Comment by Cooperstown39** [comment]
Let it run overnight but still no maps. The problem is probably on my end so I will wait for your updated installation instructions to make sure I'm doing it correctly. I'm happy to try any suggestions, don't mind being a beta site.

**Comment by M91** [comment]
> Let it run overnight but still no maps. The problem is probably on my end so I will wait for your updated installation instructions to make sure I'm doing it correctly. I'm happy to try any suggestions, don't mind being a beta site.

I had the same problem and was able to fix it by adding in this bit of code to line 19-21
[EDIT] - the file i edited was client.js
> lat = obj.lat;
lon = obj.lon;
lat = parseFloat(lat);
lon = parseFloat(lon);

From of what i noticed google api does not sanitize there data anymore. i'll try to make the change. hopefully merky1 accepts it.
You do have to enable javascript api with google
https://cloud.google.com/maps-platform

**Comment by merky1** [comment]
Now that the main project is re-engaged, suggesting you work with that.  This project is still very skunkworks and requires a lot more user interaction.
